"""Download Discourse emoji PNGs into a flat directory and emit a Swift enum.

Input: emojis.json from Discourse's /emojis.json endpoint.
  Structure: { "group": [{ "name", "url", "tonable", "search_aliases" }, ...], ... }

Output:
  <out>/Emojis/
    emoji_smiley.png
    emoji_smiley_t2.png  (skin tone variants for tonable emoji)
    ...

Asset naming is deterministic: shortcode "smiley" -> "emoji_smiley".
See src/shared/shortcode.py (mirrored in Emoji+Init.swift).
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path
from urllib.parse import quote, urljoin, urlparse, urlsplit, urlunsplit
from urllib.request import Request, urlopen

from src.shared.shortcode import sanitize_shortcode_to_asset
from src.shared.naming import emoji_case_name

ALLOWED_EXTS = {".png", ".jpg", ".jpeg", ".pdf"}


def _ext_from_url(url: str, default: str = ".png") -> str:
    _, ext = os.path.splitext(urlparse(url).path)
    return (ext or default).lower()


def _download(url: str, dst: Path) -> None:
    scheme, netloc, path, query, fragment = urlsplit(url)
    try:
        netloc = netloc.encode("idna").decode("ascii")
    except UnicodeError:
        pass
    url = urlunsplit((
        scheme,
        netloc,
        quote(path, safe="/"),
        quote(query, safe="=&?"),
        quote(fragment, safe=""),
    ))
    dst.parent.mkdir(parents=True, exist_ok=True)
    req = Request(url, headers={"User-Agent": "Mozilla/5.0 (emoji-bundler)"})
    with urlopen(req, timeout=30) as resp:
        dst.write_bytes(resp.read())


def _tone_url(base_url: str, tone: int) -> str:
    """``.../waving_hand.png?v=15`` -> ``.../waving_hand/2.png?v=15``."""
    if "?" in base_url:
        path_part, query_part = base_url.rsplit("?", 1)
        query_suffix = "?" + query_part
    else:
        path_part = base_url
        query_suffix = ""

    dot_idx = path_part.rfind(".")
    if dot_idx == -1:
        return f"{path_part}/{tone}{query_suffix}"

    stem = path_part[:dot_idx]
    ext = path_part[dot_idx:]
    return f"{stem}/{tone}{ext}{query_suffix}"


def _load_emoji_json(json_path: Path) -> list[dict]:
    import json
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)
    items: list[dict] = []
    for group_entries in data.values():
        for entry in group_entries:
            items.append({
                "shortcode_with_colons": f":{entry['name']}:",
                "src": entry["url"],
                "tonable": entry.get("tonable", False),
            })
    return items


def write_swift_enum(asset_names: list[str], swift_path: Path, enum_name: str) -> None:
    """Emit ``public enum <enum_name>: String, CaseIterable, Sendable``.

    No ``.image`` property — emoji loading goes through EmojiImageCache, which
    reads flat PNGs bundled via ``.copy()``.
    """
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by emoji.sh -- do not edit\n")
    lines.append("// swiftlint:disable file_length\n")
    lines.append(f"public enum {enum_name}: String, CaseIterable, Sendable {{")
    for asset_name in sorted(asset_names):
        lines.append(f'    case {emoji_case_name(asset_name)} = "{asset_name}"')
    lines.append("}")
    lines.append("")

    swift_path.parent.mkdir(parents=True, exist_ok=True)
    swift_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True, type=Path, help="Path to emojis.json")
    ap.add_argument("--out", required=True, type=Path, help="Output directory")
    ap.add_argument("--base-url", default="", help="Base URL for relative src paths")
    ap.add_argument("--download", action="store_true", help="Actually download images")
    ap.add_argument("--incremental", action="store_true",
                    help="Keep existing assets; only fetch missing")
    ap.add_argument("--swift", default="", help="Path to emit Swift enum file")
    ap.add_argument("--enum-name", default="DiscourseEmoji", help="Swift enum name")
    ap.add_argument("--tones", action=argparse.BooleanOptionalAction, default=True,
                    help="Download skin-tone variants for tonable emojis")
    args = ap.parse_args()

    items = _load_emoji_json(args.json)
    if not items:
        print("[ERR] No emoji entries found in JSON.", file=sys.stderr)
        return 2

    flat_dir: Path = args.out / "Emojis"
    if flat_dir.exists() and not args.incremental:
        shutil.rmtree(flat_dir)
    flat_dir.mkdir(parents=True, exist_ok=True)

    base_url = args.base_url.strip()
    seen_shortcodes: set[str] = set()
    used_asset_names: set[str] = set()

    downloaded = kept = skipped = 0
    tone_downloaded = tone_kept = tone_skipped = 0

    for it in items:
        sc_with = it["shortcode_with_colons"]
        sc_key = sc_with.strip(":")
        src = it["src"]
        url = urljoin(base_url, src) if base_url else src

        if sc_key in seen_shortcodes:
            print(f"[WARN] Duplicate shortcode '{sc_with}': {url} (skipping)")
            skipped += 1
            continue
        seen_shortcodes.add(sc_key)

        asset_name = sanitize_shortcode_to_asset(sc_with)
        if asset_name in used_asset_names:
            print(f"[WARN] Asset collision for '{sc_with}' -> {asset_name} (skipping)",
                  file=sys.stderr)
            skipped += 1
            continue
        used_asset_names.add(asset_name)

        ext = _ext_from_url(url, default=".png")
        if ext not in ALLOWED_EXTS:
            print(f"[WARN] Skipping {sc_with}: extension '{ext}' not supported ({url})")
            skipped += 1
            continue

        filename = f"{asset_name}{ext}"
        image_path = flat_dir / filename

        if args.download:
            if args.incremental and image_path.exists() and image_path.stat().st_size > 0:
                kept += 1
            else:
                try:
                    _download(url, image_path)
                    downloaded += 1
                    print(f"  ↓ {sc_with} -> {asset_name}")
                except Exception as ex:
                    print(f"[WARN] Download failed for {sc_with} from {url}: {ex}",
                          file=sys.stderr)
                    skipped += 1
                    used_asset_names.discard(asset_name)
                    continue

        if args.tones and it.get("tonable", False):
            for tone in range(2, 7):
                t_asset = f"{asset_name}_t{tone}"
                t_url = _tone_url(url, tone)
                t_ext = _ext_from_url(t_url, default=ext)
                t_path = flat_dir / f"{t_asset}{t_ext}"
                used_asset_names.add(t_asset)

                if args.download:
                    if args.incremental and t_path.exists() and t_path.stat().st_size > 0:
                        tone_kept += 1
                    else:
                        try:
                            _download(t_url, t_path)
                            tone_downloaded += 1
                            print(f"  ↓ {sc_with} t{tone} -> {t_asset}")
                        except Exception as ex:
                            print(f"[WARN] Tone {tone} download failed for {sc_with}: {ex}",
                                  file=sys.stderr)
                            tone_skipped += 1
                            used_asset_names.discard(t_asset)

    if args.swift:
        swift_path = Path(args.swift).expanduser().resolve()
        write_swift_enum(list(used_asset_names), swift_path, enum_name=args.enum_name)

    print(f"[OK] Found emojis in JSON: {len(items)}")
    print(f"[OK] Assets created: {len(used_asset_names)}")
    if args.download:
        if args.incremental:
            print(f"[OK] Already present (kept): {kept}")
            print(f"[OK] Newly downloaded: {downloaded}")
        else:
            print(f"[OK] Downloaded: {downloaded}")
        if args.tones:
            if args.incremental:
                print(f"[OK] Tone variants kept: {tone_kept}")
            print(f"[OK] Tone variants downloaded: {tone_downloaded}")
            if tone_skipped:
                print(f"[WARN] Tone variants failed: {tone_skipped}")
    else:
        print("[NOTE] Images were NOT downloaded (use --download).")
    print(f"[OK] Skipped: {skipped}")
    print(f"[OK] Output: {flat_dir}")
    if args.swift:
        print(f"[OK] Swift enum: {swift_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
