"""Generate EmojiItemTable.swift — a pre-computed picker table.

Reads emojis.json + data.js, cross-references DiscourseEmoji enum cases, and
emits statically-typed EmojiItem/EmojiGroup arrays so the picker store does
no runtime JSON parsing.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from src.shared.js_parser import extract_js_object, js_obj_to_dict
from src.shared.naming import emoji_case_name
from src.shared.shortcode import sanitize_shortcode_to_asset
from src.shared.swift_emit import swift_string_literal


def _make_search_blob(name: str, aliases: list[str]) -> str:
    """Replicate Swift EmojiPickerStore.makeSearchBlob + normalizeQuery."""
    parts = [name] + aliases
    parts = [p.replace("_", " ") for p in parts]
    blob = " ".join(parts).lower().strip().replace("_", " ")
    return re.sub(r"\s+", " ", blob)


def _pretty_group_name(gid: str) -> str:
    """``smileys_&_emotion`` -> ``Smileys & Emotion``."""
    words = gid.replace("_", " ").replace("  ", " ").split(" ")
    return " ".join(w if w == "&" else (w[0].upper() + w[1:] if w else w) for w in words)


def parse_aliases(datajs_text: str) -> dict[str, list[str]]:
    """canonical -> [alias1, alias2, ...] (normalizing alias->canonical entries)."""
    raw = js_obj_to_dict(extract_js_object(datajs_text, "aliases"))
    result: dict[str, list[str]] = {}
    for key, val in raw.items():
        if isinstance(val, list):
            result[key] = val
        elif isinstance(val, str):
            result.setdefault(val, []).append(key)
    return result


def parse_enum_asset_names(enum_path: Path) -> dict[str, str]:
    """Extract ``rawValue -> caseName`` from DiscourseEmoji enum."""
    text = enum_path.read_text(encoding="utf-8")
    pairs = re.findall(r'case\s+(\w+)\s*=\s*"([^"]+)"', text)
    return {raw: case for case, raw in pairs}


CANONICAL_GROUP_ORDER = [
    "smileys_&_emotion",
    "people_&_body",
    "animals_&_nature",
    "food_&_drink",
    "travel_&_places",
    "activities",
    "objects",
    "symbols",
    "flags",
]

GROUP_ICONS: dict[str, str] = {
    "smileys_&_emotion": "emoji_grinning_face",
    "people_&_body":     "emoji_waving_hand",
    "animals_&_nature":  "emoji_monkey",
    "food_&_drink":      "emoji_grapes",
    "travel_&_places":   "emoji_globe_showing_europe_africa",
    "activities":        "emoji_jack_o_lantern",
    "objects":           "emoji_glasses",
    "symbols":           "emoji_atm_sign",
    "flags":             "emoji_chequered_flag",
}

DEFAULT_ICON = "emoji_red_question_mark"


def generate_item_table(
    emojis_json: dict[str, list[dict]],
    canonical_to_aliases: dict[str, list[str]],
    valid_assets: dict[str, str],
) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by emoji.sh -- do not edit")
    lines.append("")
    lines.append("// swiftlint:disable file_length")
    lines.append("")
    lines.append("enum EmojiItemTable {")

    known_set = set(CANONICAL_GROUP_ORDER)
    groups_with_entries = [g for g in emojis_json.keys() if emojis_json[g]]
    ordered_known = [g for g in CANONICAL_GROUP_ORDER if g in groups_with_entries]
    ordered_unknown = sorted(g for g in groups_with_entries if g not in known_set)
    group_order = ordered_known + ordered_unknown

    lines.append("    static let groups: [EmojiGroup] = [")
    for gid in group_order:
        display_name = _pretty_group_name(gid)
        icon_asset = GROUP_ICONS.get(gid, DEFAULT_ICON)
        icon_case = valid_assets.get(icon_asset) or emoji_case_name(icon_asset)
        lines.append(
            f"        EmojiGroup("
            f"id: {swift_string_literal(gid)}, "
            f"displayName: {swift_string_literal(display_name)}, "
            f"discourseIcon: .{icon_case}"
            f"),"
        )
    lines.append("    ]")
    lines.append("")

    total = 0
    skipped_dup = 0
    skipped_missing = 0
    group_prop_names: list[tuple[str, str]] = []

    for gid in group_order:
        entries = emojis_json[gid]
        items: list[str] = []

        seen: set[str] = set()
        for entry in entries:
            name = entry["name"]
            if name in seen:
                skipped_dup += 1
                print(f"    [SKIP] duplicate '{name}' in group '{gid}'")
                continue
            seen.add(name)
            tonable = entry.get("tonable", False)
            search_aliases = entry.get("search_aliases", [])

            asset_name = sanitize_shortcode_to_asset(f":{name}:")
            case_name = valid_assets.get(asset_name)
            if case_name is None:
                skipped_missing += 1
                print(f"    [SKIP] no enum case for '{name}' (asset: {asset_name}) "
                      f"in group '{gid}'")
                continue

            extra_aliases = canonical_to_aliases.get(name, [])
            all_aliases = search_aliases + extra_aliases
            blob = _make_search_blob(name, all_aliases)

            aliases_literal = ", ".join(swift_string_literal(a) for a in search_aliases)
            tonable_str = "true" if tonable else "false"

            items.append(
                f"        EmojiItem("
                f"id: {swift_string_literal(asset_name)}, "
                f"emoji: .{case_name}, "
                f"baseName: {swift_string_literal(name)}, "
                f"groupId: {swift_string_literal(gid)}, "
                f"tonable: {tonable_str}, "
                f"aliases: [{aliases_literal}], "
                f"searchBlob: {swift_string_literal(blob)}"
                f"),"
            )
            total += 1

        prop_name = "_" + re.sub(r"[^A-Za-z0-9]+", "_", gid).strip("_")
        group_prop_names.append((gid, prop_name))
        lines.append(f"    private static let {prop_name}: [EmojiItem] = [")
        lines.extend(items)
        lines.append("    ]")
        lines.append("")

    lines.append("    static let entries: [String: [EmojiItem]] = [")
    for gid, prop_name in group_prop_names:
        lines.append(f"        {swift_string_literal(gid)}: {prop_name},")
    lines.append("    ]")
    lines.append("}")
    lines.append("")

    skipped = skipped_dup + skipped_missing
    print(f"  {len(group_order)} groups, {total} entries, {skipped} skipped "
          f"({skipped_dup} duplicate, {skipped_missing} missing asset)")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate static EmojiItemTable.swift from emojis.json + data.js"
    )
    ap.add_argument("--json", required=True, type=Path, help="Path to emojis.json")
    ap.add_argument("--datajs", required=True, type=Path, help="Path to data.js")
    ap.add_argument("--enum-file", required=True, type=Path,
                    help="Path to DiscourseEmoji.swift (for asset validation)")
    ap.add_argument("--out", required=True, type=Path, help="Output Swift file path")
    args = ap.parse_args()

    print("[1/4] Loading emojis.json...")
    emojis_json = json.loads(args.json.read_text(encoding="utf-8"))
    entry_count = sum(len(v) for v in emojis_json.values())
    print(f"  {len(emojis_json)} groups, {entry_count} entries")

    print("[2/4] Parsing data.js for aliases...")
    canonical_to_aliases = parse_aliases(args.datajs.read_text(encoding="utf-8"))
    print(f"  {len(canonical_to_aliases)} canonical entries with aliases")

    print("[3/4] Reading DiscourseEmoji enum for asset validation...")
    valid_assets = parse_enum_asset_names(args.enum_file)
    print(f"  {len(valid_assets)} valid asset names")

    print("[4/4] Generating EmojiItemTable.swift...")
    swift_content = generate_item_table(emojis_json, canonical_to_aliases, valid_assets)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(swift_content, encoding="utf-8")
    print(f"  Written: {args.out}")

    print("[OK] Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
