"""Generate Swift lookup tables from Discourse's data.js.

Emits three files into ``--out-dir``:
  - EmojiAliasTable.swift         (alias -> canonical, canonical -> [aliases])
  - EmojiReplacementTable.swift   (Unicode char -> shortcode, emoticon -> shortcode)
  - EmojiToneTable.swift          (set of tonable shortcodes)
"""

from __future__ import annotations

import argparse
from pathlib import Path

from src.shared.js_parser import (
    extract_js_array,
    extract_js_object,
    js_array_to_list,
    js_obj_to_dict,
)
from src.shared.swift_emit import chunk_pairs, swift_string_literal


def parse_aliases(text: str) -> dict[str, list[str]]:
    return js_obj_to_dict(extract_js_object(text, "aliases"))


def parse_replacements(text: str) -> dict[str, str]:
    return js_obj_to_dict(extract_js_object(text, "replacements"))


def parse_translations(text: str) -> dict[str, str]:
    return js_obj_to_dict(extract_js_object(text, "translations"))


def parse_tonable(text: str) -> list[str]:
    return js_array_to_list(extract_js_array(text, "tonableEmojis"))


def generate_alias_table(aliases: dict[str, list[str]]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by emoji.sh -- do not edit")
    lines.append("")
    lines.append("// swiftlint:disable file_length")
    lines.append("")
    lines.append("enum EmojiAliasTable {")

    inverted: dict[str, str] = {}
    for canonical, alias_list in sorted(aliases.items()):
        for alias in alias_list:
            if alias not in inverted:
                inverted[alias] = canonical
    sorted_pairs = sorted(inverted.items())
    chunks = chunk_pairs(sorted_pairs)

    for idx, chunk in enumerate(chunks):
        lines.append(f"    private static let _aliases{idx}: [String: String] = [")
        for alias, canonical in chunk:
            lines.append(
                f"        {swift_string_literal(alias)}: {swift_string_literal(canonical)},"
            )
        lines.append("    ]")
        lines.append("")

    lines.append("    /// Alias name -> canonical name")
    if len(chunks) == 1:
        lines.append("    static let aliases: [String: String] = _aliases0")
    else:
        lines.append("    static let aliases: [String: String] = {")
        lines.append("        var d = _aliases0")
        for i in range(1, len(chunks)):
            lines.append(f"        d.merge(_aliases{i}, uniquingKeysWith: {{ _, new in new }})")
        lines.append("        return d")
        lines.append("    }()")
    lines.append("")

    lines.append("    /// Canonical name -> alias names (for search augmentation)")
    lines.append("    static let canonicalToAliases: [String: [String]] = [")
    for canonical in sorted(aliases.keys()):
        alias_list = aliases[canonical]
        items = ", ".join(swift_string_literal(a) for a in sorted(alias_list))
        lines.append(f"        {swift_string_literal(canonical)}: [{items}],")
    lines.append("    ]")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_replacement_table(
    replacements: dict[str, str], translations: dict[str, str]
) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by emoji.sh -- do not edit")
    lines.append("")
    lines.append("// swiftlint:disable file_length")
    lines.append("")
    lines.append("enum EmojiReplacementTable {")

    sorted_replacements = sorted(replacements.items(), key=lambda x: x[1])
    chunks = chunk_pairs(sorted_replacements, chunk_size=500)

    for idx, chunk in enumerate(chunks):
        lines.append(f"    private static let _unicode{idx}: [String: String] = [")
        for char, shortcode in chunk:
            lines.append(
                f"        {swift_string_literal(char)}: {swift_string_literal(shortcode)},"
            )
        lines.append("    ]")
        lines.append("")

    lines.append("    /// Unicode emoji character -> canonical shortcode")
    if len(chunks) == 1:
        lines.append("    static let unicodeToShortcode: [String: String] = _unicode0")
    else:
        lines.append("    static let unicodeToShortcode: [String: String] = {")
        lines.append("        var d = _unicode0")
        for i in range(1, len(chunks)):
            lines.append(f"        d.merge(_unicode{i}, uniquingKeysWith: {{ _, new in new }})")
        lines.append("        return d")
        lines.append("    }()")
    lines.append("")

    lines.append("    /// Emoticon text -> canonical shortcode")
    lines.append("    static let emoticonToShortcode: [String: String] = [")
    for emoticon, shortcode in sorted(translations.items(), key=lambda x: x[1]):
        lines.append(
            f"        {swift_string_literal(emoticon)}: {swift_string_literal(shortcode)},"
        )
    lines.append("    ]")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_tone_table(tonable: list[str]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by emoji.sh -- do not edit")
    lines.append("")
    lines.append("enum EmojiToneTable {")
    lines.append("    /// Emoji shortcodes that support skin tones")
    lines.append("    static let tonableEmojis: Set<String> = [")
    for name in sorted(set(tonable)):
        lines.append(f"        {swift_string_literal(name)},")
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate Swift emoji lookup tables from Discourse data.js"
    )
    ap.add_argument("--datajs", required=True, type=Path, help="Path to data.js")
    ap.add_argument("--out-dir", required=True, type=Path,
                    help="Output directory for generated Swift files")
    args = ap.parse_args()

    text = args.datajs.read_text(encoding="utf-8")
    args.out_dir.mkdir(parents=True, exist_ok=True)

    print("[1/3] Parsing aliases...")
    aliases = parse_aliases(text)
    total_aliases = sum(len(v) for v in aliases.values())
    print(f"  Found {len(aliases)} canonical entries with {total_aliases} total aliases")
    alias_path = args.out_dir / "EmojiAliasTable.swift"
    alias_path.write_text(generate_alias_table(aliases), encoding="utf-8")
    print(f"  Written: {alias_path}")

    print("[2/3] Parsing replacements and translations...")
    replacements = parse_replacements(text)
    translations = parse_translations(text)
    print(f"  Found {len(replacements)} Unicode replacements, "
          f"{len(translations)} emoticon translations")
    replacement_path = args.out_dir / "EmojiReplacementTable.swift"
    replacement_path.write_text(
        generate_replacement_table(replacements, translations), encoding="utf-8"
    )
    print(f"  Written: {replacement_path}")

    print("[3/3] Parsing tonable emojis...")
    tonable = parse_tonable(text)
    print(f"  Found {len(tonable)} tonable emojis")
    tone_path = args.out_dir / "EmojiToneTable.swift"
    tone_path.write_text(generate_tone_table(tonable), encoding="utf-8")
    print(f"  Written: {tone_path}")

    print("[OK] Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
