"""Split a Discourse SVG sprite into per-icon PDF assets + Swift enum.

Orchestrates sprite parsing, SVG→PDF conversion, xcassets sync, and Swift
enum emission. The heavy lifting lives in sibling modules:

  src/icon/svg_sprite.py  — parse sprite, emit standalone SVGs
  src/icon/pdf.py         — cairosvg bridge
  src/icon/xcassets.py    — xcassets catalog I/O
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from src.icon.pdf import svgs_to_pdfs
from src.icon.svg_sprite import (
    extract_svg_block,
    parse_symbols,
    write_svg_files,
)
from src.icon.xcassets import (
    delete_orphan_imagesets,
    ensure_xcassets_root,
    imageset_pdf_exists,
    write_imageset,
)
from src.shared.naming import icon_case_name, safe_asset_name


def write_swift_enum(symbol_ids: list[str], swift_path: Path, enum_name: str) -> None:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by icon.sh -- do not edit\n")
    lines.append("// swiftlint:disable file_length\n")
    lines.append("import SwiftUI\n")
    lines.append("/// ref: https://github.com/discourse/discourse/blob/main/lib/svg_sprite.rb")
    lines.append(f"public enum {enum_name}: String, CaseIterable, Sendable {{")
    for sid in sorted(symbol_ids):
        asset_name = safe_asset_name(sid)
        lines.append(f'    case {icon_case_name(asset_name)} = "{asset_name}"')
    lines.append("}")
    lines.append("")
    lines.append(f"extension {enum_name} {{")
    lines.append("    public var image: Image { Image(self.rawValue, bundle: .module) }")
    lines.append("}")
    lines.append("")

    swift_path.parent.mkdir(parents=True, exist_ok=True)
    swift_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Split Discourse SVG sprite into per-icon assets and xcassets."
    )
    ap.add_argument("--input", "-i", required=True,
                    help="Path to sprite file (.svg or Discourse svg-*.js)")
    ap.add_argument("--out", "-o", required=True, help="Output directory")
    ap.add_argument("--svg-dir", default="svgs", help="Subdir under --out for SVGs")
    ap.add_argument("--pdf-dir", default="pdfs", help="Subdir under --out for PDFs")
    ap.add_argument("--xcassets", default="",
                    help="Path to generate an .xcassets catalog")
    ap.add_argument("--swift", default="",
                    help="Path to emit a Swift enum file")
    ap.add_argument("--enum-name", default="DiscourseIcon", help="Swift enum name")
    ap.add_argument("--filter", default="",
                    help="Regex to include only matching symbol ids")
    ap.add_argument("--incremental", action="store_true",
                    help="With --xcassets: skip icons whose imageset/pdf already "
                         "exist at the destination; delete orphan imagesets.")
    args = ap.parse_args(argv)

    in_path = Path(args.input).expanduser().resolve()
    out_root = Path(args.out).expanduser().resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    sprite_text = in_path.read_text(encoding="utf-8", errors="ignore")
    icons = parse_symbols(extract_svg_block(sprite_text))

    if args.filter:
        rx = re.compile(args.filter)
        icons = [ic for ic in icons if rx.search(ic.symbol_id)]
        if not icons:
            print("Filter removed all icons; nothing to do.", file=sys.stderr)
            return 2

    xcassets_dir = (
        Path(args.xcassets).expanduser().resolve() if args.xcassets else None
    )

    if args.incremental and xcassets_dir is not None:
        icons_to_process = [
            ic for ic in icons
            if not imageset_pdf_exists(xcassets_dir, safe_asset_name(ic.symbol_id))
        ]
    else:
        icons_to_process = icons

    kept = len(icons) - len(icons_to_process)

    symbol_to_svg = write_svg_files(icons_to_process, out_root / args.svg_dir)
    symbol_to_pdf = svgs_to_pdfs(symbol_to_svg, out_root / args.pdf_dir)

    deleted = 0
    if xcassets_dir is not None:
        ensure_xcassets_root(xcassets_dir)
        for sid, pdf_path in symbol_to_pdf.items():
            write_imageset(xcassets_dir, safe_asset_name(sid), pdf_path)
        expected = {safe_asset_name(ic.symbol_id) for ic in icons}
        deleted = delete_orphan_imagesets(xcassets_dir, expected)

    if args.swift:
        swift_path = Path(args.swift).expanduser().resolve()
        write_swift_enum([ic.symbol_id for ic in icons], swift_path,
                         enum_name=args.enum_name)

    manifest = {
        "input": str(in_path),
        "count": len(icons),
        "processed": len(icons_to_process),
        "icons": [
            {
                "id": ic.symbol_id,
                "viewBox": ic.viewbox,
                "svg": str(symbol_to_svg[ic.symbol_id]),
                "pdf": str(symbol_to_pdf[ic.symbol_id]),
            }
            for ic in icons_to_process
        ],
    }
    (out_root / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )

    generated = len(icons_to_process)
    print(f"Done. {kept} kept, {generated} generated, {deleted} deleted "
          f"(total expected: {len(icons)}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
